config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"

  resources :recipes

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :label, presence: true
  
  has_many :quantities, inverse_of: :ingredient
  has_many :recipes, through: :quantities

  before_save :sanitize_label

  private
    def sanitize_label
      self.label = strip_tags(self.label)
    end
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  validates :amount, presence: true
  validates :ingredient, presence: true

  belongs_to :recipe, inverse_of: :quantities
  belongs_to :ingredient, inverse_of: :quantities

  accepts_nested_attributes_for :ingredient, reject_if: :all_blank

  before_save :sanitize_amount

  def ingredient_attributes=(ingredient_attributes)
    unless self.amount.blank?
      ingredient = Ingredient.find_or_create_by(label: ingredient_attributes[:label])
      self.ingredient = ingredient
    end
  end

  private
    def sanitize_amount
      self.amount = strip_tags(self.amount)
    end
end

app/models/recipe.rb
include ActionView::Helpers::SanitizeHelper

class Recipe < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :instructions, presence: true

  has_many :quantities, inverse_of: :recipe
  has_many :ingredients, through: :quantities
  has_many :uploads, inverse_of: :recipe

  accepts_nested_attributes_for :quantities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :uploads, reject_if: :all_blank, allow_destroy: true

  before_save :santize_properties

  def santize_properties
    [:title, :description, :instructions].each{|prop| self.send("#{prop}=", strip_tags(self.send("#{prop}")))}
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :recipe, inverse_of: :uploads
  has_attached_file :local_image,
                    path: ":rails_root/public/system/:attachment/:id/:style/:basename.:extension",
                    url:  "/system/:attachment/:id/:style/:basename.:extension"

  has_attached_file :image,
                      styles: {
                        thumb: '64x64#',
                        small: '200x200#',
                        medium: '600x600>',
                        big: '1000x1000>'
                      },
                      convert_options: {all: '-strip'},
                      storage: :s3,
                      s3_credentials: {
                        bucket: ENV['AWS_BUCKET'],
                        access_key_id: ENV['AWS_ACCESS_KEY'],
                        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
                      },
                      s3_headers: {
                        'Expires' => 1.year.from_now.httpdate,
                        'Content-Disposition' => 'attachment'
                      },
                      bucket: ENV['AWS_BUCKET'],
                      url: ":s3_domain_url",
                      path: "images/:id/:style/:filename"

  after_save :queue_upload_to_s3

  validates_attachment :local_image,
                       presence: true,
                       content_type: { content_type: /\Aimage\/.*\Z/ },
                       size: { in: 0..4.megabytes }
  validates_attachment :image,
                       content_type: { content_type: /\Aimage\/.*\Z/ }

  validates :recipe, presence: true

  def queue_upload_to_s3
    Delayed::Job.enqueue UploadJob.new(id) if local_image? && local_image_updated_at_changed?
  end

  def upload_to_s3
    self.image = Paperclip.io_adapters.for local_image
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :get_recipe, only: [:show, :edit, :destroy, :update]
  before_filter :maybe_build_objects, only: [:edit, :new]

  def create
    @recipe = Recipe.create(recipe_params)
    
    if @recipe.valid?
      redirect_to @recipe
    else
      flash[:error] = "There were problems creating your recipe"
      render action: "new"
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted successfully"
    redirect_to recipes_url
  end

  def edit
  end

  def index
    @recipes = Recipe.all
  end

  def new
  end

  def show
  end

  def update
    if @recipe.update_attributes(recipe_params)
      flash[:success] = "Recipe successfully updated"
      redirect_to @recipe
    else
      flash.now[:error] = "There were problems updating your recipe"
      render action: "edit"
    end
  end

  protected
    def get_recipe
      @recipe = Recipe.find_by id: params[:id]
      unless @recipe
        flash.now[:error] = "Could not find that recipe"
        redirect_to recipes_url
      end
    end

    def maybe_build_objects
      @recipe = Recipe.new if !@recipe
      @recipe.quantities.build if @recipe.quantities.empty?
      @recipe.quantities.first.build_ingredient if !@recipe.quantities.first.ingredient
      @recipe.uploads.build if @recipe.uploads.empty?
    end

  private
    def recipe_params
      params.require(:recipe).permit(
        :title, 
        :description, 
        :instructions,
        {
          uploads_attributes: [:local_image, :id, :_destroy]
        },
        {
          quantities_attributes: [
            :id, 
            :amount, 
            :_destroy,
            { ingredient_attributes: [:label] }
          ]
        }
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Recipe Book
    = stylesheet_link_tag 'application', media: 'all', data: { turbolinks_track: true }
    = javascript_include_tag 'application', data: { turbolinks_track: true }
    = csrf_meta_tags

    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }

  %body{ "ng-app" => "RecipebookApp" }
    .container
      = render "shared/primary_navbar"

      = yield

app/views/quantities/_quantity.html.haml
%tr
  %td
    = quantity.amount
  %td
    = quantity.ingredient.label

app/views/recipes/_actions.html.haml
.actions
  = link_to content_tag(:span, "", class: "glyphicon glyphicon-pencil"), edit_recipe_url(recipe), title: "Edit Recipe", data: { toggle: "tooltip" }, class: "#{("primary" if primary == "edit")}" if recipe ||= nil
  = link_to content_tag(:span, "", class: "glyphicon glyphicon-plus"), new_recipe_url, title: "Create a New Recipe", data: { toggle: "tooltip" }, class: "#{("primary" if primary == "create")}"

app/views/recipes/_form.html.haml
%section.recipe
  = form_for @recipe, method: @recipe.persisted? ? "put" : "post", role: "form", multipart: true do |f|
    .row
      .col-xs-12.col-sm-6.col-md-6.col-lg-5.col-lg-offset-1
        %fieldset
          %legend
            About This Recipe

          .form-group
            = f.label :title, class: "control-label"
            = f.text_field :title, class: "form-control"

          .form-group
            = f.label :description, class: "control-label"
            = f.text_area :description, class: "form-control", rows: 3
            %p.help-block
              No <code>HTML</code> allowed. Markdown okay.

          .form-group
            = f.label :instructions, class: "control-label"
            = f.text_area :instructions, class: "form-control", rows: 5
            %p.help-block
              No <code>HTML</code> allowed. Markdown okay.

          .form-group
            = f.fields_for :uploads do |upload|
              = render 'upload_fields', f: upload

      .col-xs-12.col-sm-6.col-md-6.col-lg-5
        %fieldset
          %legend
            Ingredients

          .form-group.ingredients
            = f.fields_for :quantities do |quantity|
              = render 'quantity_fields', f: quantity

          .form-group
            = link_to_add_association "#{content_tag(:span, "", class: "glyphicon glyphicon-plus")} Add Ingredient".html_safe, f, :quantities, wrap_object: Proc.new {|q| q.build_ingredient; q }, class: "btn btn-xs btn-success", data: { association_insertion_node: ".ingredients", association_insertion_method: "append" }

    .row
      .col-xs-12.col-sm-6.col-sm-offset-6
        .form-group
          = submit_tag "Submit", class: "btn btn-primary"
          = link_to "Cancel", @recipe.persisted? ? @recipe : recipes_url, class: "btn btn-default"

app/views/recipes/_quantity_fields.html.haml
.nested-fields
  = f.text_field :amount, size: 3, required: true, placeholder: "1 lbs"

  = f.fields_for :ingredient do |ingredient|
    = ingredient.text_field :label, required: true, placeholder: "Bacon"

  = link_to_remove_association content_tag(:span, "", class: "glyphicon glyphicon-minus"), f, class: "btn btn-xs btn-link"

app/views/recipes/_recipe.html.haml
.media
  = link_to !recipe.uploads.empty? && image_tag((recipe.uploads.last.image? ? recipe.uploads.last.image.url(:thumb) : recipe.uploads.last.image.url(:thumb)), width: 64, height: 64), @recipe, class: "media-left"
  .media-body
    %h4.media-heading
      = link_to recipe.title, recipe
    = recipe.description

app/views/recipes/_upload_fields.html.haml
- if f.object.persisted?
  %span.thumbnail
    = image_tag (f.object.image? ? f.object.image.url(:medium) : f.object.local_image.url(:medium)), width: "100%"

= f.label :local_image, "Recipe Photo"
= f.file_field :local_image

app/views/recipes/edit.html.haml
.page-header 
  %h1
    Edit Recipe
    %small
      = @recipe.title

= render "form"

app/views/recipes/index.html.haml
%section.recipes
  
  = render @recipes

  = render "actions", primary: "create"

app/views/recipes/new.html.haml
.page-header
  %h1
    Create a new Recipe

= render "form"

app/views/recipes/show.html.haml
%section.recipe{"ng-controller" => "RecipeController as recipe"}
  .row
    .jumbotron.col-lg-10.col-lg-offset-1{class: !@recipe.uploads.empty? && "with-image", style: !@recipe.uploads.empty? && "background-image:url('#{@recipe.uploads.last.image? ? @recipe.uploads.last.image.url : @recipe.uploads.last.local_image.url}')"}
      %h1 #{@recipe.title}
      .description
        :markdown
          #{@recipe.description}
  .row
    %section.ingredients.col-md-6.col-lg-5.col-md-push-6
      %header
        %h3 Ingredients
      %article
        %table.table.table-condensed
          = render @recipe.quantities

    %section.instructions.col-md-6.col-lg-5.col-lg-offset-1.col-md-pull-6.col-lg-pull-5
      %header
        %h3 Instructions
      %article
        :markdown
          #{@recipe.instructions}

  = render "actions", primary: "edit", recipe: @recipe

app/views/shared/_primary_navbar.html.haml
%nav.navbar.navbar-default{ role: "navigation" }
  .container-fluid
    .navbar-header
      = link_to "#{image_tag("logo.svg", width: 32, height: 32, class: "pull-left", style: "margin: -8px 10px 0 0;")} My Recipe Book".html_safe, root_url, class: "navbar-brand"

    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "All Recipes", recipes_url